# Generated by Codex on 2026-06-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('image', '图片')], default='image', max_length=20)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('nearby_text', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='documents.document')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='documentasset',
            index=models.Index(fields=['document', 'asset_type', 'position'], name='documents_d_documen_47cfb5_idx'),
        ),
    ]
