# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentasset_ocr'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentasset',
            name='vision_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documentasset',
            name='vision_status',
            field=models.CharField(
                choices=[
                    ('pending', '待处理'),
                    ('success', '成功'),
                    ('skipped', '跳过'),
                    ('failed', '失败'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='documentasset',
            name='vision_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
